# Site settings
title: "Colin Pennington"                         
description: "Programmer."  
baseurl: ""                                
url: "https://cpennington-de.github.io"      

# Author details
author:
  name: "Colin Pennington"                      
  email: "colinpennington@cox.net"          
  bio: "Working on mainframe disaster recovery and mondernization since 2021."  
  location: "Bentonville, Arkansas"                
#  image: "/assets/images/profile.jpg"      

# Social links (customize as needed)
social:
  github: "https://github.com/cpennington-de"
  linkedin: "www.linkedin.com/in/colin-blake-pennington"

# Jekyll & Build settings
markdown: kramdown                         
theme: minima                              
plugins:
  - jekyll-feed                           
  - jekyll-seo-tag                      


nav:
  - title: "About"
    url: /about
  - title: "Portfolio"
    url: /portfolio
  - title: "Contact"
    url: /contact
